dist: zesty
language: generic

before_install:
  # Install clang 4.0
  - sudo apt-get update
  - sudo apt-get install clang-4.0
  # Install Linuxbrew
  - git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version
  # Install Buck
  - brew tap facebook/fb
  - brew install buck
  - buck --version

script:
  - mv .buckconfig.local.travis .buckconfig.local && buck build :main
