// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flutter.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "flutter.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class FlutterDataPointDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<FlutterDataPoint> {
} _FlutterDataPoint_default_instance_;
class FlutterDataDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<FlutterData> {
} _FlutterData_default_instance_;

namespace protobuf_flutter_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlutterDataPoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlutterDataPoint, entity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlutterDataPoint, metric_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlutterDataPoint, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlutterData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlutterData, points_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(FlutterDataPoint)},
  { 8, -1, sizeof(FlutterData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_FlutterDataPoint_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_FlutterData_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "flutter.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _FlutterDataPoint_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _FlutterData_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _FlutterDataPoint_default_instance_.DefaultConstruct();
  _FlutterData_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\rflutter.proto\"A\n\020FlutterDataPoint\022\016\n\006e"
      "ntity\030\001 \001(\t\022\016\n\006metric\030\002 \001(\t\022\r\n\005value\030\003 \001"
      "(\001\"0\n\013FlutterData\022!\n\006points\030\001 \003(\0132\021.Flut"
      "terDataPointb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 140);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "flutter.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_flutter_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FlutterDataPoint::kEntityFieldNumber;
const int FlutterDataPoint::kMetricFieldNumber;
const int FlutterDataPoint::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FlutterDataPoint::FlutterDataPoint()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_flutter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FlutterDataPoint)
}
FlutterDataPoint::FlutterDataPoint(const FlutterDataPoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  entity_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.entity().size() > 0) {
    entity_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entity_);
  }
  metric_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.metric().size() > 0) {
    metric_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.metric_);
  }
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:FlutterDataPoint)
}

void FlutterDataPoint::SharedCtor() {
  entity_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  metric_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = 0;
  _cached_size_ = 0;
}

FlutterDataPoint::~FlutterDataPoint() {
  // @@protoc_insertion_point(destructor:FlutterDataPoint)
  SharedDtor();
}

void FlutterDataPoint::SharedDtor() {
  entity_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  metric_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FlutterDataPoint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FlutterDataPoint::descriptor() {
  protobuf_flutter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_flutter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FlutterDataPoint& FlutterDataPoint::default_instance() {
  protobuf_flutter_2eproto::InitDefaults();
  return *internal_default_instance();
}

FlutterDataPoint* FlutterDataPoint::New(::google::protobuf::Arena* arena) const {
  FlutterDataPoint* n = new FlutterDataPoint;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FlutterDataPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:FlutterDataPoint)
  entity_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  metric_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = 0;
}

bool FlutterDataPoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FlutterDataPoint)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string entity = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_entity()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->entity().data(), this->entity().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "FlutterDataPoint.entity"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string metric = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_metric()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->metric().data(), this->metric().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "FlutterDataPoint.metric"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FlutterDataPoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FlutterDataPoint)
  return false;
#undef DO_
}

void FlutterDataPoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FlutterDataPoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string entity = 1;
  if (this->entity().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entity().data(), this->entity().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FlutterDataPoint.entity");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->entity(), output);
  }

  // string metric = 2;
  if (this->metric().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->metric().data(), this->metric().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FlutterDataPoint.metric");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->metric(), output);
  }

  // double value = 3;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:FlutterDataPoint)
}

::google::protobuf::uint8* FlutterDataPoint::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FlutterDataPoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string entity = 1;
  if (this->entity().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->entity().data(), this->entity().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FlutterDataPoint.entity");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->entity(), target);
  }

  // string metric = 2;
  if (this->metric().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->metric().data(), this->metric().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "FlutterDataPoint.metric");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->metric(), target);
  }

  // double value = 3;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:FlutterDataPoint)
  return target;
}

size_t FlutterDataPoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FlutterDataPoint)
  size_t total_size = 0;

  // string entity = 1;
  if (this->entity().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->entity());
  }

  // string metric = 2;
  if (this->metric().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->metric());
  }

  // double value = 3;
  if (this->value() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FlutterDataPoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FlutterDataPoint)
  GOOGLE_DCHECK_NE(&from, this);
  const FlutterDataPoint* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FlutterDataPoint>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FlutterDataPoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FlutterDataPoint)
    MergeFrom(*source);
  }
}

void FlutterDataPoint::MergeFrom(const FlutterDataPoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FlutterDataPoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.entity().size() > 0) {

    entity_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.entity_);
  }
  if (from.metric().size() > 0) {

    metric_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.metric_);
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void FlutterDataPoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FlutterDataPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlutterDataPoint::CopyFrom(const FlutterDataPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FlutterDataPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlutterDataPoint::IsInitialized() const {
  return true;
}

void FlutterDataPoint::Swap(FlutterDataPoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FlutterDataPoint::InternalSwap(FlutterDataPoint* other) {
  entity_.Swap(&other->entity_);
  metric_.Swap(&other->metric_);
  std::swap(value_, other->value_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FlutterDataPoint::GetMetadata() const {
  protobuf_flutter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_flutter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FlutterDataPoint

// string entity = 1;
void FlutterDataPoint::clear_entity() {
  entity_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& FlutterDataPoint::entity() const {
  // @@protoc_insertion_point(field_get:FlutterDataPoint.entity)
  return entity_.GetNoArena();
}
void FlutterDataPoint::set_entity(const ::std::string& value) {
  
  entity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FlutterDataPoint.entity)
}
#if LANG_CXX11
void FlutterDataPoint::set_entity(::std::string&& value) {
  
  entity_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FlutterDataPoint.entity)
}
#endif
void FlutterDataPoint::set_entity(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  entity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FlutterDataPoint.entity)
}
void FlutterDataPoint::set_entity(const char* value, size_t size) {
  
  entity_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FlutterDataPoint.entity)
}
::std::string* FlutterDataPoint::mutable_entity() {
  
  // @@protoc_insertion_point(field_mutable:FlutterDataPoint.entity)
  return entity_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* FlutterDataPoint::release_entity() {
  // @@protoc_insertion_point(field_release:FlutterDataPoint.entity)
  
  return entity_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void FlutterDataPoint::set_allocated_entity(::std::string* entity) {
  if (entity != NULL) {
    
  } else {
    
  }
  entity_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), entity);
  // @@protoc_insertion_point(field_set_allocated:FlutterDataPoint.entity)
}

// string metric = 2;
void FlutterDataPoint::clear_metric() {
  metric_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& FlutterDataPoint::metric() const {
  // @@protoc_insertion_point(field_get:FlutterDataPoint.metric)
  return metric_.GetNoArena();
}
void FlutterDataPoint::set_metric(const ::std::string& value) {
  
  metric_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FlutterDataPoint.metric)
}
#if LANG_CXX11
void FlutterDataPoint::set_metric(::std::string&& value) {
  
  metric_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FlutterDataPoint.metric)
}
#endif
void FlutterDataPoint::set_metric(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  metric_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FlutterDataPoint.metric)
}
void FlutterDataPoint::set_metric(const char* value, size_t size) {
  
  metric_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FlutterDataPoint.metric)
}
::std::string* FlutterDataPoint::mutable_metric() {
  
  // @@protoc_insertion_point(field_mutable:FlutterDataPoint.metric)
  return metric_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* FlutterDataPoint::release_metric() {
  // @@protoc_insertion_point(field_release:FlutterDataPoint.metric)
  
  return metric_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void FlutterDataPoint::set_allocated_metric(::std::string* metric) {
  if (metric != NULL) {
    
  } else {
    
  }
  metric_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metric);
  // @@protoc_insertion_point(field_set_allocated:FlutterDataPoint.metric)
}

// double value = 3;
void FlutterDataPoint::clear_value() {
  value_ = 0;
}
double FlutterDataPoint::value() const {
  // @@protoc_insertion_point(field_get:FlutterDataPoint.value)
  return value_;
}
void FlutterDataPoint::set_value(double value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:FlutterDataPoint.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FlutterData::kPointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FlutterData::FlutterData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_flutter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FlutterData)
}
FlutterData::FlutterData(const FlutterData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      points_(from.points_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:FlutterData)
}

void FlutterData::SharedCtor() {
  _cached_size_ = 0;
}

FlutterData::~FlutterData() {
  // @@protoc_insertion_point(destructor:FlutterData)
  SharedDtor();
}

void FlutterData::SharedDtor() {
}

void FlutterData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FlutterData::descriptor() {
  protobuf_flutter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_flutter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FlutterData& FlutterData::default_instance() {
  protobuf_flutter_2eproto::InitDefaults();
  return *internal_default_instance();
}

FlutterData* FlutterData::New(::google::protobuf::Arena* arena) const {
  FlutterData* n = new FlutterData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FlutterData::Clear() {
// @@protoc_insertion_point(message_clear_start:FlutterData)
  points_.Clear();
}

bool FlutterData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FlutterData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .FlutterDataPoint points = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_points()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FlutterData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FlutterData)
  return false;
#undef DO_
}

void FlutterData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FlutterData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .FlutterDataPoint points = 1;
  for (unsigned int i = 0, n = this->points_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->points(i), output);
  }

  // @@protoc_insertion_point(serialize_end:FlutterData)
}

::google::protobuf::uint8* FlutterData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FlutterData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .FlutterDataPoint points = 1;
  for (unsigned int i = 0, n = this->points_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->points(i), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:FlutterData)
  return target;
}

size_t FlutterData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FlutterData)
  size_t total_size = 0;

  // repeated .FlutterDataPoint points = 1;
  {
    unsigned int count = this->points_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->points(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FlutterData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FlutterData)
  GOOGLE_DCHECK_NE(&from, this);
  const FlutterData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FlutterData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FlutterData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FlutterData)
    MergeFrom(*source);
  }
}

void FlutterData::MergeFrom(const FlutterData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FlutterData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  points_.MergeFrom(from.points_);
}

void FlutterData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FlutterData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlutterData::CopyFrom(const FlutterData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FlutterData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlutterData::IsInitialized() const {
  return true;
}

void FlutterData::Swap(FlutterData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FlutterData::InternalSwap(FlutterData* other) {
  points_.InternalSwap(&other->points_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FlutterData::GetMetadata() const {
  protobuf_flutter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_flutter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FlutterData

// repeated .FlutterDataPoint points = 1;
int FlutterData::points_size() const {
  return points_.size();
}
void FlutterData::clear_points() {
  points_.Clear();
}
const ::FlutterDataPoint& FlutterData::points(int index) const {
  // @@protoc_insertion_point(field_get:FlutterData.points)
  return points_.Get(index);
}
::FlutterDataPoint* FlutterData::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:FlutterData.points)
  return points_.Mutable(index);
}
::FlutterDataPoint* FlutterData::add_points() {
  // @@protoc_insertion_point(field_add:FlutterData.points)
  return points_.Add();
}
::google::protobuf::RepeatedPtrField< ::FlutterDataPoint >*
FlutterData::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:FlutterData.points)
  return &points_;
}
const ::google::protobuf::RepeatedPtrField< ::FlutterDataPoint >&
FlutterData::points() const {
  // @@protoc_insertion_point(field_list:FlutterData.points)
  return points_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
