cxx_library(
    name = 'event',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    srcs = glob(['*.cpp']),
    exported_linker_flags = [
        '-lz',
        '-lrt',
    ],
)
