cxx_library(
    name = 'flutter',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    headers = glob(['*.h', 'protobuf/*.h']),
    srcs = glob(['*.cpp', 'protobuf/*.cc']),
    deps = [
        '//common:common',
        '//event:event',
        '//networking:networking',
        '//stats:stats',
    ],
)
