cxx_library(
    name = 'networking',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    srcs = glob(['*.cpp']),
    deps = [
        '//common:common',
        '//event:event',
        '//json:json',
        '//stats:stats',
        '//cryptopp:cryptopp',
    ],
)
