cxx_library(
    name = 'networking',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    srcs = glob(['*.cpp']),
    deps = [
        '//common:common',
        '//event:event',
        'nlohmann.json//:json',
        '//stats:stats',
        '//crypto:crypto',
    ],
)
