# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


apple_bundle(
  name = 'Stun',
  binary = ':StunBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  deps = [
    ':StunExtension',
  ],
)

# Stun main app

apple_resource(
  name = 'StunResources',
  files = glob(['Resources/*.png']),
  dirs = [],
)

apple_binary(
  name = 'StunBinary',
  deps = [
    ':StunResources',
    '//stun:stun',
  ],
  preprocessor_flags = ['-fobjc-arc', '-Wno-objc-designated-initializers'],
  headers = glob([
    'Stun/*.h',
    'Stun/*.hh',
  ]),
  srcs = glob([
    'Stun/*.m',
    'Stun/*.mm',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/NetworkExtension.framework',
  ],
)

# Stun network extension

apple_binary(
  name = 'StunExtensionBinary',
  preprocessor_flags = ['-fobjc-arc', '-Wno-objc-designated-initializers'],
  headers = glob([
    'StunExtension/*.h',
  ]),
  srcs = glob([
    'StunExtension/*.m',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/NetworkExtension.framework',
  ],
  linker_flags = ['-e', '_NSExtensionMain'],
)

apple_bundle(
  name = 'StunExtension',
  binary = ':StunExtensionBinary',
  extension = 'appex',
  info_plist = 'StunExtension/Info.plist',
)

# Package

apple_package(
  name = 'StunPackage',
  bundle = ':Stun',
)
