# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


apple_bundle(
  name = 'Stun',
  binary = ':StunBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  deps = [
    ':StunPacketTunnel',
  ],
)

# Stun main app

apple_resource(
  name = 'StunResources',
  files = glob(['Resources/*.png']),
  dirs = [],
)

apple_binary(
  name = 'StunBinary',
  deps = [
    ':StunResources',
  ],
  preprocessor_flags = ['-fobjc-arc', '-Wno-objc-designated-initializers'],
  headers = glob([
    'Stun/*.h',
    'Stun/*.hh',
  ]),
  srcs = glob([
    'Stun/*.m',
    'Stun/*.mm',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/NetworkExtension.framework',
  ],
  entitlements_file = 'Stun.entitlements',
)

# Stun network extension

apple_binary(
  name = 'StunPacketTunnelBinary',
  preprocessor_flags = ['-fobjc-arc', '-Wno-objc-designated-initializers'],
  headers = glob([
    'StunPacketTunnel/*.h',
    'StunPacketTunnel/*.hh',
  ]),
  srcs = glob([
    'StunPacketTunnel/*.m',
    'StunPacketTunnel/*.mm',
  ]),
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/NetworkExtension.framework',
  ],
  deps = [
    "//stun:stun",
  ],
  linker_flags = ['-e', '_NSExtensionMain'],
  entitlements_file = 'StunPacketTunnel.entitlements',
)

apple_bundle(
  name = 'StunPacketTunnel',
  binary = ':StunPacketTunnelBinary',
  extension = 'appex',
  info_plist = 'StunPacketTunnel/Info.plist',
  xcode_product_type = 'com.apple.product-type.app-extension',
)

# Package

apple_package(
  name = 'StunPackage',
  bundle = ':Stun',
)
