cxx_library(
    name = 'minilzo',
    exported_headers = [
        'minilzo.h',
        'lzoconf.h',
        'lzodefs.h',
    ],
    srcs = [
        'minilzo.c'
    ],
    visibility = ['PUBLIC'],
)
