cxx_library(
    name = 'crypto',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    srcs = glob(['*.cpp']),
    deps = [
        '//common:common',
        'weidai11.cryptopp//:cryptopp',
        'oberhumer.minilzo//:minilzo',
    ],
)
