cxx_library(
    name = 'crypto',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    srcs = glob(['*.cpp']),
    deps = [
        '//common:common',
        '//third-party:cryptopp',
        '//third-party/minilzo:minilzo',
    ],
)
