cxx_library(
    name = 'crypto',
    visibility = [
        'PUBLIC',
    ],
    exported_headers = glob(['*.h']),
    srcs = glob(['*.cpp']),
    deps = [
        '//cryptopp:cryptopp',
        '//common:common',
    ],
)
